fastlane_version "2.54.4"

default_platform :ios

lane :cleanup do |options|
  artifacts = []
  artifacts << "." + ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'] if ENV['CORDOVA_IOS_RELEASE_BUILD_PATH']
  artifacts << "." + ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'] if ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH']
  artifacts << lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH] if lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
  UI.verbose(artifacts)
  copy_artifacts(
    target_path: "artifacts/" + lane_context[SharedValues::LANE_NAME],
    artifacts: artifacts
  )

  #sh("cp ." + ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'] + " \"../artifacts2/"+ lane_context[SharedValues::LANE_NAME]+"/foo.ipa\"") if ENV['CORDOVA_IOS_RELEASE_BUILD_PATH']
  #sh("cp ." + ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'] + " \"../artifacts2/"+ lane_context[SharedValues::LANE_NAME]+"/foo.apk\"") if ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH']

  # Reset the git repo to a clean state, but leave our artifacts in place
  #reset_git_repo(
  #  exclude: "artifacts"
  #)
end

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Build Debug Debug Ionic"
  lane :build_debug_debug_ionic do
    ionic(
      platform: 'ios',
      type: 'development',
      prod: false,
      release: false
    )
    cleanup
  end

  desc "Build Debug Ionic"
  lane :build_debug_ionic do
    ionic(
      platform: 'ios',
      type: 'development',
      prod: true,
      release: false
    )
    cleanup
  end

  desc "Build Debug Cordova"
  lane :build_debug_cordova do
    cordova(
      platform: 'ios',
      type: 'development',
      release: false
    )
    cleanup
  end

  desc "Build Debug Native"
  lane :build_debug_native do
    match
    name = "FastlaneExample" # TODO Extract
    xcworkspacepath = "platforms/ios/" + name + ".xcworkspace" # TODO Extract
    gym(
      configuration: 'Debug',
      workspace: xcworkspacepath,
      scheme: name,
      export_method: 'development'
    )
    cleanup
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Build Release Ionic"
  lane :build_release_ionic do
    match(type: 'appstore')
    ionic(
      platform: 'ios',
      prod: true,
      release: true
    )
    cleanup
  end

  desc "Build Release Cordova"
  lane :build_release_cordova do
    match(type: 'appstore')
    cordova(
      platform: 'ios',
      release: true
    )
    cleanup
  end

  desc "Build Release Native"
  lane :build_release_native do
    match(type: 'appstore')
    name = "FastlaneExample" # TODO Extract
    xcworkspacepath = "platforms/ios/" + name + ".xcworkspace" # TODO Extract
    gym(
      configuration: 'Release',
      workspace: xcworkspacepath,
      scheme: name #,
      #export_method: 'development'
    )
    cleanup
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Build Debug Debug Ionic"
  lane :build_debug_debug_ionic do
    ionic(
      platform: 'android',
      release: false,
      prod: false
    )
    cleanup
  end

  desc "Build Debug Ionic"
  lane :build_debug_ionic do
    ionic(
      platform: 'android',
      release: false,
      prod: true
    )
    cleanup
  end

  desc "Build Debug Cordova"
  lane :build_debug_cordova do
    cordova(
      platform: 'android',
      release: false
    )
    cleanup
  end

  desc "Build Debug Native"
  lane :build_debug_native do
    gradle(
      task: 'assemble',
      build_type: 'Debug',
      project_dir: 'platforms/android'
    )
    cleanup
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build Release Ionic"
  lane :build_release_ionic do
    ionic(
      platform: 'android',
      release: true,
      prod: true,

      keystore_path: '../Dropbox/zaehlerstand.keystore',
      keystore_alias: 'Zaehlerstand',
      keystore_password: '123',
      key_password: '123'
    )
    cleanup
  end

  desc "Build Release Cordova"
  lane :build_release_cordova do
    cordova(
      platform: 'android',
      release: true,

      keystore_path: '../Dropbox/Zaehlerstand.keystore',
      keystore_alias: 'Zaehlerstand',
      keystore_password: '123',
      key_password: '123'
    )
    cleanup
  end

  desc "Build Release Native"
  lane :build_release_native do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: 'platforms/android',

      properties: {
        "android.injected.signing.store.file" => "../Dropbox/Zaehlerstand.keystore",
        "android.injected.signing.store.password" => "123",
        "android.injected.signing.key.alias" => "Zaehlerstand",
        "android.injected.signing.key.password" => "123",
      }
    )
    cleanup
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
